---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helloworld.rvolykh.github.com
  resources:
  - copytopods
  - mcps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helloworld.rvolykh.github.com
  resources:
  - copytopods/finalizers
  - mcps/finalizers
  verbs:
  - update
- apiGroups:
  - helloworld.rvolykh.github.com
  resources:
  - copytopods/status
  - mcps/status
  verbs:
  - get
  - patch
  - update
