apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-sample
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80


# kubectl port-forward pod/nginx-pod-sample 8080:80
# curl http://localhost:8080
